### ISSUE TITLE
There is a vtk warning when loading a transducer model

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/OpenLIFU-python#108]
After loading a transducer model there is a warning

```
[VTK] Bad table range: [0, -1]
```

I haven't noticed any problems caused by this yet.

The fix for this could be in openlifu, we'll see. This is what we use to get the model: https://github.com/OpenwaterHealth/OpenLIFU-python/blob/06f8756b254d627f6f6919d5ed7b705d15a99a21/src/openlifu/xdc/transducer.py#L73

**Comment by medmssaouri** [comment]
According to this 3D slicer discussion https://discourse.slicer.org/t/vtklookuptable-bad-table-range-0-1/8718/3,  when constructing a vtkpolydata for an MRML, color mapping should be set in MRML using a MRML color node and not in the vtkpolydata object.
