### ISSUE TITLE
Fix pytest not being installed automatically 

### ISSUE THREAD

**Issue by medmssaouri** [OpenwaterHealth/OpenLIFU-python#111]
Optional dependencies are not always installed automatically when launching:
```
pip install -e .
```
I believe the installation command should be updated to something like the following for development mode:
```
pip install -e .[all]
```

**Comment by ebrahimebrahim** [comment]
For development mode `pip install -e .[dev]` includes the tests: https://github.com/OpenwaterHealth/OpenLIFU-python/blob/369f8d4fbc6e772068fc8037f061733d0cff8655/pyproject.toml#L53
That resolves the issue right?

**Comment by medmssaouri** [comment]
That should resolve the issue. 
For clarification, i opened this issue to update the install section in README. For example, having two subsections, classic install and dev install (the case where dependencies like tests should be installed)

**Comment by ebrahimebrahim** [comment]
Agreed. This is also connected to #11
