### ISSUE TITLE
Fix 'write_session' to handle new subjects

### ISSUE THREAD

**Issue by sadhana-r** [OpenwaterHealth/OpenLIFU-python#137]
When writing a session to database, the session directory should be created if it doesn't already exist to handle situations where a new subject has been created.

- [ ]  Bug fix to create session directory if it doesn't exist
- [ ]  Write unit test

**Comment by ebrahimebrahim** [comment]
This is kind of related to #124 also

**Comment by sadhana-r** [comment]
Oh I can address that in this PR then.
