### ISSUE TITLE
Regressions with minimal solution analysis

### ISSUE THREAD

**Issue by ltetrel** [OpenwaterHealth/OpenLIFU-python#141]
After testing the functionality from https://github.com/OpenwaterHealth/OpenLIFU-python/pull/140 and comparing with the expected solution analysis output from Matlab (only `mainlobe_pnp_MPa` ATM) , there are some regressions. This can come from two sources:
1. Simulation output: there are some differences in the k-wave simulations output between the matlab and python generated-one.
2. [Incorrect mask computation](https://github.com/OpenwaterHealth/OpenLIFU-python/blob/main/src/openlifu/bf/offset_grid.py): and more specifically when we define the mask in the transducer reference, This depends on [geo.py](https://github.com/OpenwaterHealth/OpenLIFU-python/blob/17a6983465b6021adca059ef53839d609aa43c56/src/openlifu/geo.py#L38) which was not tested previously.

`tests/test_mask_focus.py` and `tests/test_offset_grid.py` would need to be updated accordingly.

**Comment by ebrahimebrahim** [comment]
Can test directly that the mailobe pnp is computed correctly by creating a fake pnp volume with two peaks, with a smaller peak closer to the focus, and make sure it's producing the peak value around the focus

**Comment by ltetrel** [comment]
After some digging, the issue is not in the simulation output values:
1. There are indeed differences in the simulation output values but it is negligible, the general shape is coherent (we see an oblong-shaped spot where the focus is).
2. When checking the maximum value of  `p_min` (which is a coherent method for the location of the mainlobe) in both matlab and python, there are close.

The issue is on the implementation of the focus mask which is not coherent. Probably in `src/openlifu/bf/offset_grid.py` (to compare with `offset_grid.m` in matlab).

**Comment by peterhollender** [comment]
I'm getting large regressions in the simulation output when I use elements that are tilted (two flat matrix arrays tilted toward one another). For 2, 8x8 arrays, 5mm pitch, arranged along a 150mm ROC with a 1mm gap, focused at (0,0,50) in water, I can see grating lobes in the ax=20mm slice. However, the OpenLIFU python output is not symmetric across the elevation axis, despite the focus, delays, and elements all being symmetric in elevation. 
OpenLIFUPython output 
(![image](https://github.com/user-attachments/assets/90feb741-90f4-4084-875e-d7ed480b280f)
opw_neuromod_sw (MATLAB) output: 
![image](https://github.com/user-attachments/assets/c284b5eb-4599-49aa-94c0-17932fdbd25f)
