### ISSUE TITLE
Undefined items in `database.py`

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/OpenLIFU-python#80]
There is a number of undefined items in `src/openlifu/db/database.py`, as though perhaps there is a missing dependency

for example `Volume`, `UltrasoundSystem`, `Standoff`, `generate_standoff_mask`, `Session`

(In the case of `Session` it looks like it's just a missing import)

Are many of these things slated to be implemented but not implemented yet? If so then similarly to #79 we should raise an exception indicating that

**Comment by peterhollender** [comment]
Correct, they aren’t implemented yet. Did a bulk conversion of the Matlab
to Python, and hadn’t implemented to those classes yet. Agreed they should
raise exceptions in the meantime.

**Comment by ebrahimebrahim** [comment]
In that case this is a duplicate of #79, so closing it. It is to be resolved in #79
