### ISSUE TITLE
test_first notebook throws "unexpected keyword argument 'grid_weights'"

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/OpenLIFU-python#9]
The [test_first notebook](https://github.com/OpenwaterHealth/OpenLIFU-python/blob/46d73e8d70886911890a8e20351ea15d27ed8460/test_notebooks/test_first.ipynb) contains this error for me:

```txt
TypeError: kWaveArray.get_distributed_source_signal() got an unexpected keyword argument 'grid_weights'
```

in reference to this line:
https://github.com/OpenwaterHealth/OpenLIFU-python/blob/46d73e8d70886911890a8e20351ea15d27ed8460/pyfus/sim/kwave_if.py#L64

**Comment by peterhollender** [comment]
Didn't get the backwards-compatibility to the unpatched `k-wave-python` correct. Closed by 81f894190bae8dd0477208ca3d14f55f79c715ee. The use of cached gridweights is being discussed at [](https://github.com/waltsims/k-wave-python/issues/342), so this may need to get updated in the future if we can come up with an official solution to the performance bottleneck my modifications were working on.

**Comment by ebrahimebrahim** [comment]
@peterhollender TY for the fix! Two large PRs are coming shortly for #5 -- let's avoid pushing to directly to main from now on :sweat_smile:

**Comment by ebrahimebrahim** [comment]
@peterhollender Would you be willing to retract the commit 81f8941 from the main branch and make a separate PR that updates the notebooks to fix this error? The alternative would be for me to rebase #16 and #17 onto the new main branch, but there are a few reasons I think it might be better to retract the commit and use #16 and #17 instead:

- the commits in #16 are more separated based on what they do
- the commits in #16 reference the issue they are associated with

This is better for requirements traceability. Let me know what you think and if you want me to rebase the PRs I can still do that with some effort

**Comment by peterhollender** [comment]
Sure, I'll retract it.

**Comment by peterhollender** [comment]
Also, the fix for that bug is actually a change in `pyfus/sim/kwave_if.py`, which is going to move, so I'll fix it in `src/openlifu/sim/kwave_if.py` after we merge #16?
