### ISSUE TITLE
Replace warning messages with info level for overwrites in database

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/OpenLIFU-python#94]
To edit a session in the database one can load the `Session`, make changes to the object, and then use `Database.add_session` with on_conflict=’overwrite’. This should work once #92 is fixed. However, it raises a warning as though overwriting a session is a weird thing to do. Maybe we can clean up the API to have a function with the clear intent of editing an existing session.

Depends on #92

**Comment by medmssaouri** [comment]
@ebrahimebrahim i replaced warning messages with info level for overwrite of all "add_" functions of database class
